global using System;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Drawing;
global using System.Drawing.Drawing2D;
global using System.IO;
global using System.Media;
global using System.Runtime.InteropServices;
global using System.Windows.Forms;