//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Settings.Settings.Other {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class StringCollectionSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static StringCollectionSettings defaultInstance = ((StringCollectionSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StringCollectionSettings())));
        
        public static StringCollectionSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
