global using Microsoft.WindowsAPICodePack.ExtendedLinguisticServices.Resources;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Runtime.ConstrainedExecution;
global using System.Runtime.InteropServices;
global using System.Runtime.Serialization;
global using System.Text;
global using System.Threading;
