//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Core.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class PaletteColourSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PaletteColourSettings defaultInstance = ((PaletteColourSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PaletteColourSettings())));
        
        public static PaletteColourSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
