#region BSD License
/*
 * Use of this source code is governed by a BSD-style
 * license or other governing licenses that can be found in the LICENSE.md file or at
 * https://raw.githubusercontent.com/Krypton-Suite/Extended-Toolkit/master/LICENSE
 */
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Settings
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class ColourStringSettings : global::System.Configuration.ApplicationSettingsBase
    {

        private static ColourStringSettings defaultInstance = ((ColourStringSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ColourStringSettings())));

        public static ColourStringSettings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlternativeNormalTextColour
        {
            get
            {
                return ((string)(this["AlternativeNormalTextColour"]));
            }
            set
            {
                this["AlternativeNormalTextColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BaseColour
        {
            get
            {
                return ((string)(this["BaseColour"]));
            }
            set
            {
                this["BaseColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BorderColour
        {
            get
            {
                return ((string)(this["BorderColour"]));
            }
            set
            {
                this["BorderColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomColourOne
        {
            get
            {
                return ((string)(this["CustomColourOne"]));
            }
            set
            {
                this["CustomColourOne"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomColourTwo
        {
            get
            {
                return ((string)(this["CustomColourTwo"]));
            }
            set
            {
                this["CustomColourTwo"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomColourThree
        {
            get
            {
                return ((string)(this["CustomColourThree"]));
            }
            set
            {
                this["CustomColourThree"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomColourFour
        {
            get
            {
                return ((string)(this["CustomColourFour"]));
            }
            set
            {
                this["CustomColourFour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomColourFive
        {
            get
            {
                return ((string)(this["CustomColourFive"]));
            }
            set
            {
                this["CustomColourFive"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomColourSix
        {
            get
            {
                return ((string)(this["CustomColourSix"]));
            }
            set
            {
                this["CustomColourSix"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomColourSeven
        {
            get
            {
                return ((string)(this["CustomColourSeven"]));
            }
            set
            {
                this["CustomColourSeven"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomColourEight
        {
            get
            {
                return ((string)(this["CustomColourEight"]));
            }
            set
            {
                this["CustomColourEight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomColourNine
        {
            get
            {
                return ((string)(this["CustomColourNine"]));
            }
            set
            {
                this["CustomColourNine"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomColourTen
        {
            get
            {
                return ((string)(this["CustomColourTen"]));
            }
            set
            {
                this["CustomColourTen"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTextColourOne
        {
            get
            {
                return ((string)(this["CustomTextColourOne"]));
            }
            set
            {
                this["CustomTextColourOne"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTextColourTwo
        {
            get
            {
                return ((string)(this["CustomTextColourTwo"]));
            }
            set
            {
                this["CustomTextColourTwo"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTextColourThree
        {
            get
            {
                return ((string)(this["CustomTextColourThree"]));
            }
            set
            {
                this["CustomTextColourThree"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTextColourFour
        {
            get
            {
                return ((string)(this["CustomTextColourFour"]));
            }
            set
            {
                this["CustomTextColourFour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTextColourFive
        {
            get
            {
                return ((string)(this["CustomTextColourFive"]));
            }
            set
            {
                this["CustomTextColourFive"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTextColourSix
        {
            get
            {
                return ((string)(this["CustomTextColourSix"]));
            }
            set
            {
                this["CustomTextColourSix"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTextColourSeven
        {
            get
            {
                return ((string)(this["CustomTextColourSeven"]));
            }
            set
            {
                this["CustomTextColourSeven"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTextColourEight
        {
            get
            {
                return ((string)(this["CustomTextColourEight"]));
            }
            set
            {
                this["CustomTextColourEight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTextColourNine
        {
            get
            {
                return ((string)(this["CustomTextColourNine"]));
            }
            set
            {
                this["CustomTextColourNine"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTextColourTen
        {
            get
            {
                return ((string)(this["CustomTextColourTen"]));
            }
            set
            {
                this["CustomTextColourTen"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DarkColour
        {
            get
            {
                return ((string)(this["DarkColour"]));
            }
            set
            {
                this["DarkColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DisabledControlColour
        {
            get
            {
                return ((string)(this["DisabledControlColour"]));
            }
            set
            {
                this["DisabledControlColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LinkDisabledColour
        {
            get
            {
                return ((string)(this["LinkDisabledColour"]));
            }
            set
            {
                this["LinkDisabledColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LinkFocusedColour
        {
            get
            {
                return ((string)(this["LinkFocusedColour"]));
            }
            set
            {
                this["LinkFocusedColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LinkHoverColour
        {
            get
            {
                return ((string)(this["LinkHoverColour"]));
            }
            set
            {
                this["LinkHoverColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LinkNormalColour
        {
            get
            {
                return ((string)(this["LinkNormalColour"]));
            }
            set
            {
                this["LinkNormalColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LinkVisitedColour
        {
            get
            {
                return ((string)(this["LinkVisitedColour"]));
            }
            set
            {
                this["LinkVisitedColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LightColour
        {
            get
            {
                return ((string)(this["LightColour"]));
            }
            set
            {
                this["LightColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LightestColour
        {
            get
            {
                return ((string)(this["LightestColour"]));
            }
            set
            {
                this["LightestColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MenuTextColour
        {
            get
            {
                return ((string)(this["MenuTextColour"]));
            }
            set
            {
                this["MenuTextColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StatusStripTextColour
        {
            get
            {
                return ((string)(this["StatusStripTextColour"]));
            }
            set
            {
                this["StatusStripTextColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RibbonTabTextColour
        {
            get
            {
                return ((string)(this["RibbonTabTextColour"]));
            }
            set
            {
                this["RibbonTabTextColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DisabledTextColour
        {
            get
            {
                return ((string)(this["DisabledTextColour"]));
            }
            set
            {
                this["DisabledTextColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NormalTextColour
        {
            get
            {
                return ((string)(this["NormalTextColour"]));
            }
            set
            {
                this["NormalTextColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PressedTextColour
        {
            get
            {
                return ((string)(this["PressedTextColour"]));
            }
            set
            {
                this["PressedTextColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FocusedTextColour
        {
            get
            {
                return ((string)(this["FocusedTextColour"]));
            }
            set
            {
                this["FocusedTextColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MediumColour
        {
            get
            {
                return ((string)(this["MediumColour"]));
            }
            set
            {
                this["MediumColour"] = value;
            }
        }
    }
}
