//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Settings.Settings.Globals {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class GlobalTypefaceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalTypefaceSettings defaultInstance = ((GlobalTypefaceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalTypefaceSettings())));
        
        public static GlobalTypefaceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 8.25pt, style=Bold")]
        public global::System.Drawing.Font BoldTypeface {
            get {
                return ((global::System.Drawing.Font)(this["BoldTypeface"]));
            }
            set {
                this["BoldTypeface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 8.25pt")]
        public global::System.Drawing.Font CueTypeface {
            get {
                return ((global::System.Drawing.Font)(this["CueTypeface"]));
            }
            set {
                this["CueTypeface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 8.25pt")]
        public global::System.Drawing.Font NormalTypeface {
            get {
                return ((global::System.Drawing.Font)(this["NormalTypeface"]));
            }
            set {
                this["NormalTypeface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 8.25pt")]
        public global::System.Drawing.Font MessageBoxButtonsTypeface {
            get {
                return ((global::System.Drawing.Font)(this["MessageBoxButtonsTypeface"]));
            }
            set {
                this["MessageBoxButtonsTypeface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 8.25pt")]
        public global::System.Drawing.Font MessageBoxContentTypeface {
            get {
                return ((global::System.Drawing.Font)(this["MessageBoxContentTypeface"]));
            }
            set {
                this["MessageBoxContentTypeface"] = value;
            }
        }
    }
}
