#region MIT License
/*
 *
 * MIT License
 *
 * Copyright (c) 2017 - 2023 Krypton Suite
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class AllMergedColourSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AllMergedColourSettings defaultInstance = ((AllMergedColourSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AllMergedColourSettings())));
        
        public static AllMergedColourSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color BaseColour {
            get {
                return ((global::System.Drawing.Color)(this["BaseColour"]));
            }
            set {
                this["BaseColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DarkColour {
            get {
                return ((global::System.Drawing.Color)(this["DarkColour"]));
            }
            set {
                this["DarkColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color MediumColour {
            get {
                return ((global::System.Drawing.Color)(this["MediumColour"]));
            }
            set {
                this["MediumColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LightColour {
            get {
                return ((global::System.Drawing.Color)(this["LightColour"]));
            }
            set {
                this["LightColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LightestColour {
            get {
                return ((global::System.Drawing.Color)(this["LightestColour"]));
            }
            set {
                this["LightestColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourOne {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourOne"]));
            }
            set {
                this["CustomColourOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourTwo {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourTwo"]));
            }
            set {
                this["CustomColourTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourThree {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourThree"]));
            }
            set {
                this["CustomColourThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourFour {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourFour"]));
            }
            set {
                this["CustomColourFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourFive {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourFive"]));
            }
            set {
                this["CustomColourFive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourSix {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourSix"]));
            }
            set {
                this["CustomColourSix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomTextColourOne {
            get {
                return ((global::System.Drawing.Color)(this["CustomTextColourOne"]));
            }
            set {
                this["CustomTextColourOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomTextColourTwo {
            get {
                return ((global::System.Drawing.Color)(this["CustomTextColourTwo"]));
            }
            set {
                this["CustomTextColourTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomTextColourThree {
            get {
                return ((global::System.Drawing.Color)(this["CustomTextColourThree"]));
            }
            set {
                this["CustomTextColourThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomTextColourFour {
            get {
                return ((global::System.Drawing.Color)(this["CustomTextColourFour"]));
            }
            set {
                this["CustomTextColourFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomTextColourFive {
            get {
                return ((global::System.Drawing.Color)(this["CustomTextColourFive"]));
            }
            set {
                this["CustomTextColourFive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomTextColourSix {
            get {
                return ((global::System.Drawing.Color)(this["CustomTextColourSix"]));
            }
            set {
                this["CustomTextColourSix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LinkFocusedColour {
            get {
                return ((global::System.Drawing.Color)(this["LinkFocusedColour"]));
            }
            set {
                this["LinkFocusedColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LinkHoverColour {
            get {
                return ((global::System.Drawing.Color)(this["LinkHoverColour"]));
            }
            set {
                this["LinkHoverColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LinkNormalColour {
            get {
                return ((global::System.Drawing.Color)(this["LinkNormalColour"]));
            }
            set {
                this["LinkNormalColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LinkVisitedColour {
            get {
                return ((global::System.Drawing.Color)(this["LinkVisitedColour"]));
            }
            set {
                this["LinkVisitedColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color BorderColour {
            get {
                return ((global::System.Drawing.Color)(this["BorderColour"]));
            }
            set {
                this["BorderColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DisabledControlColour {
            get {
                return ((global::System.Drawing.Color)(this["DisabledControlColour"]));
            }
            set {
                this["DisabledControlColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color MenuTextColour {
            get {
                return ((global::System.Drawing.Color)(this["MenuTextColour"]));
            }
            set {
                this["MenuTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color StatusStripTextColour {
            get {
                return ((global::System.Drawing.Color)(this["StatusStripTextColour"]));
            }
            set {
                this["StatusStripTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color RibbonTabTextColour {
            get {
                return ((global::System.Drawing.Color)(this["RibbonTabTextColour"]));
            }
            set {
                this["RibbonTabTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color AlternativeNormalTextColour {
            get {
                return ((global::System.Drawing.Color)(this["AlternativeNormalTextColour"]));
            }
            set {
                this["AlternativeNormalTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DisabledTextColour {
            get {
                return ((global::System.Drawing.Color)(this["DisabledTextColour"]));
            }
            set {
                this["DisabledTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color FocusedTextColour {
            get {
                return ((global::System.Drawing.Color)(this["FocusedTextColour"]));
            }
            set {
                this["FocusedTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color NormalTextColour {
            get {
                return ((global::System.Drawing.Color)(this["NormalTextColour"]));
            }
            set {
                this["NormalTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PressedTextColour {
            get {
                return ((global::System.Drawing.Color)(this["PressedTextColour"]));
            }
            set {
                this["PressedTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LinkDisabledColour {
            get {
                return ((global::System.Drawing.Color)(this["LinkDisabledColour"]));
            }
            set {
                this["LinkDisabledColour"] = value;
            }
        }
    }
}
