//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace Krypton.Toolkit.Suite.Extended.TreeGridView.Resources;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal static class TreeGridImageResources
{
    private static global::System.Resources.ResourceManager? resourceMan;

    private static global::System.Globalization.CultureInfo? resourceCulture;

    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                resourceMan = new global::System.Resources.ResourceManager(
                    "Krypton.Toolkit.Suite.Extended.TreeGridView.Resources.TreeGridImageResources",
                    typeof(TreeGridImageResources).Assembly);
            }

            return resourceMan;
        }
    }

    internal static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    internal static System.Drawing.Bitmap CollapseIcon =>
        (System.Drawing.Bitmap)ResourceManager.GetObject("CollapseIcon", resourceCulture)!;

    internal static System.Drawing.Bitmap CollapseIcon2010 =>
        (System.Drawing.Bitmap)ResourceManager.GetObject("CollapseIcon2010", resourceCulture)!;

    internal static System.Drawing.Bitmap ExpandIcon =>
        (System.Drawing.Bitmap)ResourceManager.GetObject("ExpandIcon", resourceCulture)!;

    internal static System.Drawing.Bitmap ExpandIcon2010 =>
        (System.Drawing.Bitmap)ResourceManager.GetObject("ExpandIcon2010", resourceCulture)!;
}
