//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Settings.Settings.Controls {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class WindowLocationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static WindowLocationSettings defaultInstance = ((WindowLocationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WindowLocationSettings())));
        
        public static WindowLocationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DefaultWindowPosition {
            get {
                return ((global::System.Drawing.Point)(this["DefaultWindowPosition"]));
            }
            set {
                this["DefaultWindowPosition"] = value;
            }
        }
    }
}
