//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Settings.Settings.Palette_Explorer.General {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.0.0")]
    internal sealed partial class PaletteTypefaceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PaletteTypefaceSettings defaultInstance = ((PaletteTypefaceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PaletteTypefaceSettings())));
        
        public static PaletteTypefaceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font GlobalPaletteTypeface {
            get {
                return ((global::System.Drawing.Font)(this["GlobalPaletteTypeface"]));
            }
            set {
                this["GlobalPaletteTypeface"] = value;
            }
        }
    }
}
