//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Windows.API.Code.Pack.Dialogs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Windows.API.Code.Pack.Dialogs.Resources.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register application for restart due to bad parameters..
        /// </summary>
        internal static string ApplicationRecoverFailedToRegisterForRestartBadParameters {
            get {
                return ResourceManager.GetString("ApplicationRecoverFailedToRegisterForRestartBadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application was not registered for recovery due to bad parameters..
        /// </summary>
        internal static string ApplicationRecoveryBadParameters {
            get {
                return ResourceManager.GetString("ApplicationRecoveryBadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application failed to register for recovery..
        /// </summary>
        internal static string ApplicationRecoveryFailedToRegister {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application failed to registered for restart..
        /// </summary>
        internal static string ApplicationRecoveryFailedToRegisterForRestart {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToRegisterForRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister for recovery failed..
        /// </summary>
        internal static string ApplicationRecoveryFailedToUnregister {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToUnregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister for restart failed..
        /// </summary>
        internal static string ApplicationRecoveryFailedToUnregisterForRestart {
            get {
                return ResourceManager.GetString("ApplicationRecoveryFailedToUnregisterForRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method must be called from the registered callback method..
        /// </summary>
        internal static string ApplicationRecoveryMustBeCalledFromCallback {
            get {
                return ResourceManager.GetString("ApplicationRecoveryMustBeCalledFromCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACOnline: {1}{0}Max Charge: {2} mWh{0}Current Charge: {3} mWh{0}Discharge Rate: {4} mWh{0}Estimated Time Remaining: {5}{0}Suggested Critical Battery Charge: {6} mWh{0}Suggested Battery Warning Charge: {7} mWh{0}.
        /// </summary>
        internal static string BatteryStateStringRepresentation {
            get {
                return ResourceManager.GetString("BatteryStateStringRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelable cannot be changed while dialog is showing..
        /// </summary>
        internal static string CancelableCannotBeChanged {
            get {
                return ResourceManager.GetString("CancelableCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog caption cannot be changed while dialog is showing..
        /// </summary>
        internal static string CaptionCannotBeChanged {
            get {
                return ResourceManager.GetString("CaptionCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox text cannot be changed while dialog is showing..
        /// </summary>
        internal static string CheckBoxCannotBeChanged {
            get {
                return ResourceManager.GetString("CheckBoxCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsed control text cannot be changed while dialog is showing..
        /// </summary>
        internal static string CollapsedTextCannotBeChanged {
            get {
                return ResourceManager.GetString("CollapsedTextCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only supported on Windows 7 or newer..
        /// </summary>
        internal static string CoreHelpersRunningOn7 {
            get {
                return ResourceManager.GetString("CoreHelpersRunningOn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only supported on Windows Vista or newer..
        /// </summary>
        internal static string CoreHelpersRunningOnVista {
            get {
                return ResourceManager.GetString("CoreHelpersRunningOnVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only supported on Windows XP or newer..
        /// </summary>
        internal static string CoreHelpersRunningOnXp {
            get {
                return ResourceManager.GetString("CoreHelpersRunningOnXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog cannot have more than one control with the same name..
        /// </summary>
        internal static string DialogCollectionCannotHaveDuplicateNames {
            get {
                return ResourceManager.GetString("DialogCollectionCannotHaveDuplicateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog control must be removed from current collections first..
        /// </summary>
        internal static string DialogCollectionControlAlreadyHosted {
            get {
                return ResourceManager.GetString("DialogCollectionControlAlreadyHosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control name cannot be null or zero length..
        /// </summary>
        internal static string DialogCollectionControlNameNull {
            get {
                return ResourceManager.GetString("DialogCollectionControlNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying controls collection while dialog is showing is not supported..
        /// </summary>
        internal static string DialogCollectionModifyShowingDialog {
            get {
                return ResourceManager.GetString("DialogCollectionModifyShowingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog control name cannot be empty or null..
        /// </summary>
        internal static string DialogControlNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("DialogControlNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog controls cannot be renamed..
        /// </summary>
        internal static string DialogControlsCannotBeRenamed {
            get {
                return ResourceManager.GetString("DialogControlsCannotBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string DialogDefaultCaption {
            get {
                return ResourceManager.GetString("DialogDefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DialogDefaultContent {
            get {
                return ResourceManager.GetString("DialogDefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DialogDefaultMainInstruction {
            get {
                return ResourceManager.GetString("DialogDefaultMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded information mode cannot be changed while dialog is showing..
        /// </summary>
        internal static string ExpandedDetailsCannotBeChanged {
            get {
                return ResourceManager.GetString("ExpandedDetailsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded control label cannot be changed while dialog is showing..
        /// </summary>
        internal static string ExpandedLabelCannotBeChanged {
            get {
                return ResourceManager.GetString("ExpandedLabelCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanding state of the dialog cannot be changed while dialog is showing..
        /// </summary>
        internal static string ExpandingStateCannotBeChanged {
            get {
                return ResourceManager.GetString("ExpandingStateCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlinks cannot be enabled/disabled while dialog is showing..
        /// </summary>
        internal static string HyperlinksCannotBetSet {
            get {
                return ResourceManager.GetString("HyperlinksCannotBetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference path is invalid..
        /// </summary>
        internal static string InvalidReferencePath {
            get {
                return ResourceManager.GetString("InvalidReferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified event handler has not been registered..
        /// </summary>
        internal static string MessageManagerHandlerNotRegistered {
            get {
                return ResourceManager.GetString("MessageManagerHandlerNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred in dialog configuration..
        /// </summary>
        internal static string NativeTaskDialogConfigurationError {
            get {
                return ResourceManager.GetString("NativeTaskDialogConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments to Win32 call..
        /// </summary>
        internal static string NativeTaskDialogInternalErrorArgs {
            get {
                return ResourceManager.GetString("NativeTaskDialogInternalErrorArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog contents too complex..
        /// </summary>
        internal static string NativeTaskDialogInternalErrorComplex {
            get {
                return ResourceManager.GetString("NativeTaskDialogInternalErrorComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected internal error occurred in the Win32 call: {0:x}.
        /// </summary>
        internal static string NativeTaskDialogInternalErrorUnexpected {
            get {
                return ResourceManager.GetString("NativeTaskDialogInternalErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskDialog feature needs to load version 6 of comctl32.dll but a different version is current loaded in memory..
        /// </summary>
        internal static string NativeTaskDialogVersionError {
            get {
                return ResourceManager.GetString("NativeTaskDialogVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog owner cannot be changed while dialog is showing..
        /// </summary>
        internal static string OwnerCannotBeChanged {
            get {
                return ResourceManager.GetString("OwnerCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetThreadExecutionState call failed..
        /// </summary>
        internal static string PowerExecutionStateFailed {
            get {
                return ResourceManager.GetString("PowerExecutionStateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller had insufficient access rights to get the system battery state..
        /// </summary>
        internal static string PowerInsufficientAccessBatteryState {
            get {
                return ResourceManager.GetString("PowerInsufficientAccessBatteryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller had insufficient access rights to get the system power capabilities..
        /// </summary>
        internal static string PowerInsufficientAccessCapabilities {
            get {
                return ResourceManager.GetString("PowerInsufficientAccessCapabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get active power scheme..
        /// </summary>
        internal static string PowerManagerActiveSchemeFailed {
            get {
                return ResourceManager.GetString("PowerManagerActiveSchemeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery is not present on this system..
        /// </summary>
        internal static string PowerManagerBatteryNotPresent {
            get {
                return ResourceManager.GetString("PowerManagerBatteryNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress bar cannot be changed while dialog is showing..
        /// </summary>
        internal static string ProgressBarCannotBeChanged {
            get {
                return ResourceManager.GetString("ProgressBarCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress bar cannot be hosted in multiple dialogs..
        /// </summary>
        internal static string ProgressBarCannotBeHostedInMultipleDialogs {
            get {
                return ResourceManager.GetString("ProgressBarCannotBeHostedInMultipleDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string PropertyKeyFormatString {
            get {
                return ResourceManager.GetString("PropertyKeyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize PropVariant..
        /// </summary>
        internal static string PropVariantInitializationError {
            get {
                return ResourceManager.GetString("PropVariantInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-dimensional SafeArrays not supported..
        /// </summary>
        internal static string PropVariantMultiDimArray {
            get {
                return ResourceManager.GetString("PropVariantMultiDimArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String argument cannot be null or empty..
        /// </summary>
        internal static string PropVariantNullString {
            get {
                return ResourceManager.GetString("PropVariantNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Value type is not supported..
        /// </summary>
        internal static string PropVariantTypeNotSupported {
            get {
                return ResourceManager.GetString("PropVariantTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be cast to unsupported type..
        /// </summary>
        internal static string PropVariantUnsupportedType {
            get {
                return ResourceManager.GetString("PropVariantUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delegate: {0}, state: {1}, ping: {2}.
        /// </summary>
        internal static string RecoverySettingsFormatString {
            get {
                return ResourceManager.GetString("RecoverySettingsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command: {0} restrictions: {1}.
        /// </summary>
        internal static string RestartSettingsFormatString {
            get {
                return ResourceManager.GetString("RestartSettingsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StandardButtons cannot be changed while dialog is showing..
        /// </summary>
        internal static string StandardButtonsCannotBeChanged {
            get {
                return ResourceManager.GetString("StandardButtonsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup location cannot be changed while dialog is showing..
        /// </summary>
        internal static string StartupLocationCannotBeChanged {
            get {
                return ResourceManager.GetString("StartupLocationCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ApplicationRecoverFailedToRegisterForRestartBadParameters&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Failed to register application for restart due to bad parameters.&lt;/value&gt;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Application failed to registered for restart.&lt;/value&gt;.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;An unexpected internal error occurred in the Win32 call: {0:x}&lt;/value&gt;.
        /// </summary>
        internal static string String100 {
            get {
                return ResourceManager.GetString("String100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String101 {
            get {
                return ResourceManager.GetString("String101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;NativeTaskDialogVersionError&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String102 {
            get {
                return ResourceManager.GetString("String102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;TaskDialog feature needs to load version 6 of comctl32.dll but a different version is current loaded in memory.&lt;/value&gt;.
        /// </summary>
        internal static string String103 {
            get {
                return ResourceManager.GetString("String103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String104 {
            get {
                return ResourceManager.GetString("String104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;OwnerCannotBeChanged&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String105 {
            get {
                return ResourceManager.GetString("String105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Dialog owner cannot be changed while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String106 {
            get {
                return ResourceManager.GetString("String106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String107 {
            get {
                return ResourceManager.GetString("String107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;PowerExecutionStateFailed&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String108 {
            get {
                return ResourceManager.GetString("String108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;SetThreadExecutionState call failed.&lt;/value&gt;.
        /// </summary>
        internal static string String109 {
            get {
                return ResourceManager.GetString("String109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String110 {
            get {
                return ResourceManager.GetString("String110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;PowerInsufficientAccessBatteryState&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String111 {
            get {
                return ResourceManager.GetString("String111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;The caller had insufficient access rights to get the system battery state.&lt;/value&gt;.
        /// </summary>
        internal static string String112 {
            get {
                return ResourceManager.GetString("String112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String113 {
            get {
                return ResourceManager.GetString("String113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;PowerInsufficientAccessCapabilities&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String114 {
            get {
                return ResourceManager.GetString("String114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;The caller had insufficient access rights to get the system power capabilities.&lt;/value&gt;.
        /// </summary>
        internal static string String115 {
            get {
                return ResourceManager.GetString("String115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String116 {
            get {
                return ResourceManager.GetString("String116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;PowerManagerBatteryNotPresent&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String117 {
            get {
                return ResourceManager.GetString("String117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Battery is not present on this system.&lt;/value&gt;.
        /// </summary>
        internal static string String118 {
            get {
                return ResourceManager.GetString("String118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String119 {
            get {
                return ResourceManager.GetString("String119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ApplicationRecoveryFailedToUnregister&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ProgressBarCannotBeChanged&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String120 {
            get {
                return ResourceManager.GetString("String120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Progress bar cannot be changed while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String121 {
            get {
                return ResourceManager.GetString("String121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String122 {
            get {
                return ResourceManager.GetString("String122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ProgressBarCannotBeHostedInMultipleDialogs&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String123 {
            get {
                return ResourceManager.GetString("String123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Progress bar cannot be hosted in multiple dialogs.&lt;/value&gt;.
        /// </summary>
        internal static string String124 {
            get {
                return ResourceManager.GetString("String124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String125 {
            get {
                return ResourceManager.GetString("String125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;PropertyKeyFormatString&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String126 {
            get {
                return ResourceManager.GetString("String126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;{0}, {1}&lt;/value&gt;.
        /// </summary>
        internal static string String127 {
            get {
                return ResourceManager.GetString("String127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String128 {
            get {
                return ResourceManager.GetString("String128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;PropVariantMultiDimArray&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String129 {
            get {
                return ResourceManager.GetString("String129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Unregister for recovery failed.&lt;/value&gt;.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Multi-dimensional SafeArrays not supported.&lt;/value&gt;.
        /// </summary>
        internal static string String130 {
            get {
                return ResourceManager.GetString("String130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String131 {
            get {
                return ResourceManager.GetString("String131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;PropVariantNullString&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String132 {
            get {
                return ResourceManager.GetString("String132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;String argument cannot be null or empty.&lt;/value&gt;.
        /// </summary>
        internal static string String133 {
            get {
                return ResourceManager.GetString("String133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String134 {
            get {
                return ResourceManager.GetString("String134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;PropVariantTypeNotSupported&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String135 {
            get {
                return ResourceManager.GetString("String135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;This Value type is not supported.&lt;/value&gt;.
        /// </summary>
        internal static string String136 {
            get {
                return ResourceManager.GetString("String136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String137 {
            get {
                return ResourceManager.GetString("String137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;RecoverySettingsFormatString&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String138 {
            get {
                return ResourceManager.GetString("String138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;delegate: {0}, state: {1}, ping: {2}&lt;/value&gt;.
        /// </summary>
        internal static string String139 {
            get {
                return ResourceManager.GetString("String139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String140 {
            get {
                return ResourceManager.GetString("String140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;RestartSettingsFormatString&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String141 {
            get {
                return ResourceManager.GetString("String141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;command: {0} restrictions: {1}&lt;/value&gt;.
        /// </summary>
        internal static string String142 {
            get {
                return ResourceManager.GetString("String142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String143 {
            get {
                return ResourceManager.GetString("String143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;StandardButtonsCannotBeChanged&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String144 {
            get {
                return ResourceManager.GetString("String144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;StandardButtons cannot be changed while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String145 {
            get {
                return ResourceManager.GetString("String145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String146 {
            get {
                return ResourceManager.GetString("String146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;StartupLocationCannotBeChanged&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String147 {
            get {
                return ResourceManager.GetString("String147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Startup location cannot be changed while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String148 {
            get {
                return ResourceManager.GetString("String148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String149 {
            get {
                return ResourceManager.GetString("String149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ApplicationRecoveryFailedToUnregisterForRestart&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogBadButtonId&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String150 {
            get {
                return ResourceManager.GetString("String150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Bad button ID in closing event.&lt;/value&gt;.
        /// </summary>
        internal static string String151 {
            get {
                return ResourceManager.GetString("String151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String152 {
            get {
                return ResourceManager.GetString("String152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogButtonTextEmpty&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String153 {
            get {
                return ResourceManager.GetString("String153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Button text must be non-empty.&lt;/value&gt;.
        /// </summary>
        internal static string String154 {
            get {
                return ResourceManager.GetString("String154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String155 {
            get {
                return ResourceManager.GetString("String155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogCheckBoxTextRequiredToEnableCheckBox&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String156 {
            get {
                return ResourceManager.GetString("String156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Check box text must be provided to enable the dialog check box.&lt;/value&gt;.
        /// </summary>
        internal static string String157 {
            get {
                return ResourceManager.GetString("String157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String158 {
            get {
                return ResourceManager.GetString("String158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogCloseNonShowing&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String159 {
            get {
                return ResourceManager.GetString("String159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Unregister for restart failed.&lt;/value&gt;.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Attempting to close a non-showing dialog.&lt;/value&gt;.
        /// </summary>
        internal static string String160 {
            get {
                return ResourceManager.GetString("String160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String161 {
            get {
                return ResourceManager.GetString("String161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogDefaultCaption&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String162 {
            get {
                return ResourceManager.GetString("String162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Application&lt;/value&gt;.
        /// </summary>
        internal static string String163 {
            get {
                return ResourceManager.GetString("String163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String164 {
            get {
                return ResourceManager.GetString("String164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogDefaultContent&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String165 {
            get {
                return ResourceManager.GetString("String165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value /&gt;.
        /// </summary>
        internal static string String166 {
            get {
                return ResourceManager.GetString("String166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String167 {
            get {
                return ResourceManager.GetString("String167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogDefaultMainInstruction&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String168 {
            get {
                return ResourceManager.GetString("String168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value /&gt;.
        /// </summary>
        internal static string String169 {
            get {
                return ResourceManager.GetString("String169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String170 {
            get {
                return ResourceManager.GetString("String170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogOnlyOneDefaultControl&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String171 {
            get {
                return ResourceManager.GetString("String171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Cannot have more than one default button of a given type.&lt;/value&gt;.
        /// </summary>
        internal static string String172 {
            get {
                return ResourceManager.GetString("String172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String173 {
            get {
                return ResourceManager.GetString("String173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogProgressBarMaxValueGreaterThanMin&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String174 {
            get {
                return ResourceManager.GetString("String174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Maximum value provided must be greater than the minimum value.&lt;/value&gt;.
        /// </summary>
        internal static string String175 {
            get {
                return ResourceManager.GetString("String175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String176 {
            get {
                return ResourceManager.GetString("String176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogProgressBarMinValueGreaterThanZero&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String177 {
            get {
                return ResourceManager.GetString("String177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Minimum value provided must be a positive number.&lt;/value&gt;.
        /// </summary>
        internal static string String178 {
            get {
                return ResourceManager.GetString("String178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String179 {
            get {
                return ResourceManager.GetString("String179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ApplicationRecoveryMustBeCalledFromCallback&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogProgressBarMinValueLessThanMax&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String180 {
            get {
                return ResourceManager.GetString("String180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Minimum value provided must less than the maximum value.&lt;/value&gt;.
        /// </summary>
        internal static string String181 {
            get {
                return ResourceManager.GetString("String181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String182 {
            get {
                return ResourceManager.GetString("String182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogProgressBarValueInRange&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String183 {
            get {
                return ResourceManager.GetString("String183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Value provided must be greater than equal to the minimum value and less than the maximum value.&lt;/value&gt;.
        /// </summary>
        internal static string String184 {
            get {
                return ResourceManager.GetString("String184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String185 {
            get {
                return ResourceManager.GetString("String185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogSupportedButtonsAndButtons&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String186 {
            get {
                return ResourceManager.GetString("String186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Dialog cannot display both non-standard buttons and standard buttons.&lt;/value&gt;.
        /// </summary>
        internal static string String187 {
            get {
                return ResourceManager.GetString("String187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String188 {
            get {
                return ResourceManager.GetString("String188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogSupportedButtonsAndLinks&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String189 {
            get {
                return ResourceManager.GetString("String189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;This method must be called from the registered callback method.&lt;/value&gt;.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Dialog cannot display both non-standard buttons and command links.&lt;/value&gt;.
        /// </summary>
        internal static string String190 {
            get {
                return ResourceManager.GetString("String190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String191 {
            get {
                return ResourceManager.GetString("String191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;TaskDialogUnkownControl&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String192 {
            get {
                return ResourceManager.GetString("String192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Unknown dialog control type.&lt;/value&gt;.
        /// </summary>
        internal static string String193 {
            get {
                return ResourceManager.GetString("String193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String194 {
            get {
                return ResourceManager.GetString("String194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;PropVariantInitializationError&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String195 {
            get {
                return ResourceManager.GetString("String195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Unable to initialize PropVariant.&lt;/value&gt;.
        /// </summary>
        internal static string String196 {
            get {
                return ResourceManager.GetString("String196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String197 {
            get {
                return ResourceManager.GetString("String197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;PowerManagerActiveSchemeFailed&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String198 {
            get {
                return ResourceManager.GetString("String198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Failed to get active power scheme.&lt;/value&gt;.
        /// </summary>
        internal static string String199 {
            get {
                return ResourceManager.GetString("String199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String200 {
            get {
                return ResourceManager.GetString("String200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;PropVariantUnsupportedType&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String201 {
            get {
                return ResourceManager.GetString("String201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Cannot be cast to unsupported type.&lt;/value&gt;.
        /// </summary>
        internal static string String202 {
            get {
                return ResourceManager.GetString("String202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String203 {
            get {
                return ResourceManager.GetString("String203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;BatteryStateStringRepresentation&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;ACOnline: {1}{0}Max Charge: {2} mWh{0}Current Charge: {3} mWh{0}Discharge Rate: {4} mWh{0}Estimated Time Remaining: {5}{0}Suggested Critical Battery Charge: {6} mWh{0}Suggested Battery Warning Charge: {7} mWh{0}&lt;/value&gt;.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;CancelableCannotBeChanged&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Cancelable cannot be changed while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;CaptionCannotBeChanged&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Dialog caption cannot be changed while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ApplicationRecoveryBadParameters&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;CheckBoxCannotBeChanged&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;CheckBox text cannot be changed while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;CollapsedTextCannotBeChanged&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Collapsed control text cannot be changed while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;CoreHelpersRunningOn7&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Only supported on Windows 7 or newer.&lt;/value&gt;.
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;CoreHelpersRunningOnVista&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Application was not registered for recovery due to bad parameters.&lt;/value&gt;.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Only supported on Windows Vista or newer.&lt;/value&gt;.
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;CoreHelpersRunningOnXp&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Only supported on Windows XP or newer.&lt;/value&gt;.
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;DialogCollectionCannotHaveDuplicateNames&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Dialog cannot have more than one control with the same name.&lt;/value&gt;.
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;DialogCollectionControlAlreadyHosted&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Dialog control must be removed from current collections first.&lt;/value&gt;.
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;DialogCollectionControlNameNull&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Control name cannot be null or zero length.&lt;/value&gt;.
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;DialogCollectionModifyShowingDialog&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Modifying controls collection while dialog is showing is not supported.&lt;/value&gt;.
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;DialogControlNameCannotBeEmpty&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Dialog control name cannot be empty or null.&lt;/value&gt;.
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ApplicationRecoveryFailedToRegister&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;DialogControlsCannotBeRenamed&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Dialog controls cannot be renamed.&lt;/value&gt;.
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;DialogDefaultCaption&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Application&lt;/value&gt;.
        /// </summary>
        internal static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;DialogDefaultContent&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value /&gt;.
        /// </summary>
        internal static string String67 {
            get {
                return ResourceManager.GetString("String67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String68 {
            get {
                return ResourceManager.GetString("String68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;DialogDefaultMainInstruction&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String69 {
            get {
                return ResourceManager.GetString("String69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Application failed to register for recovery.&lt;/value&gt;.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value /&gt;.
        /// </summary>
        internal static string String70 {
            get {
                return ResourceManager.GetString("String70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String71 {
            get {
                return ResourceManager.GetString("String71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ExpandedDetailsCannotBeChanged&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String72 {
            get {
                return ResourceManager.GetString("String72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Expanded information mode cannot be changed while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String73 {
            get {
                return ResourceManager.GetString("String73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String74 {
            get {
                return ResourceManager.GetString("String74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ExpandedLabelCannotBeChanged&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String75 {
            get {
                return ResourceManager.GetString("String75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Expanded control label cannot be changed while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String76 {
            get {
                return ResourceManager.GetString("String76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String77 {
            get {
                return ResourceManager.GetString("String77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ExpandingStateCannotBeChanged&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String78 {
            get {
                return ResourceManager.GetString("String78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Expanding state of the dialog cannot be changed while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String79 {
            get {
                return ResourceManager.GetString("String79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String80 {
            get {
                return ResourceManager.GetString("String80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;HyperlinksCannotBetSet&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String81 {
            get {
                return ResourceManager.GetString("String81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Hyperlinks cannot be enabled/disabled while dialog is showing.&lt;/value&gt;.
        /// </summary>
        internal static string String82 {
            get {
                return ResourceManager.GetString("String82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String83 {
            get {
                return ResourceManager.GetString("String83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;InvalidReferencePath&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String84 {
            get {
                return ResourceManager.GetString("String84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Reference path is invalid.&lt;/value&gt;.
        /// </summary>
        internal static string String85 {
            get {
                return ResourceManager.GetString("String85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String86 {
            get {
                return ResourceManager.GetString("String86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;MessageManagerHandlerNotRegistered&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String87 {
            get {
                return ResourceManager.GetString("String87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;The specified event handler has not been registered.&lt;/value&gt;.
        /// </summary>
        internal static string String88 {
            get {
                return ResourceManager.GetString("String88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String89 {
            get {
                return ResourceManager.GetString("String89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;ApplicationRecoveryFailedToRegisterForRestart&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;NativeTaskDialogConfigurationError&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String90 {
            get {
                return ResourceManager.GetString("String90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;An error has occurred in dialog configuration.&lt;/value&gt;.
        /// </summary>
        internal static string String91 {
            get {
                return ResourceManager.GetString("String91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String92 {
            get {
                return ResourceManager.GetString("String92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;NativeTaskDialogInternalErrorArgs&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String93 {
            get {
                return ResourceManager.GetString("String93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Invalid arguments to Win32 call.&lt;/value&gt;.
        /// </summary>
        internal static string String94 {
            get {
                return ResourceManager.GetString("String94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String95 {
            get {
                return ResourceManager.GetString("String95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;NativeTaskDialogInternalErrorComplex&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String96 {
            get {
                return ResourceManager.GetString("String96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;Dialog contents too complex.&lt;/value&gt;.
        /// </summary>
        internal static string String97 {
            get {
                return ResourceManager.GetString("String97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/data&gt;.
        /// </summary>
        internal static string String98 {
            get {
                return ResourceManager.GetString("String98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;NativeTaskDialogInternalErrorUnexpected&quot; xml:space=&quot;preserve&quot;&gt;.
        /// </summary>
        internal static string String99 {
            get {
                return ResourceManager.GetString("String99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad button ID in closing event..
        /// </summary>
        internal static string TaskDialogBadButtonId {
            get {
                return ResourceManager.GetString("TaskDialogBadButtonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button text must be non-empty..
        /// </summary>
        internal static string TaskDialogButtonTextEmpty {
            get {
                return ResourceManager.GetString("TaskDialogButtonTextEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check box text must be provided to enable the dialog check box..
        /// </summary>
        internal static string TaskDialogCheckBoxTextRequiredToEnableCheckBox {
            get {
                return ResourceManager.GetString("TaskDialogCheckBoxTextRequiredToEnableCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to close a non-showing dialog..
        /// </summary>
        internal static string TaskDialogCloseNonShowing {
            get {
                return ResourceManager.GetString("TaskDialogCloseNonShowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string TaskDialogDefaultCaption {
            get {
                return ResourceManager.GetString("TaskDialogDefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TaskDialogDefaultContent {
            get {
                return ResourceManager.GetString("TaskDialogDefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TaskDialogDefaultMainInstruction {
            get {
                return ResourceManager.GetString("TaskDialogDefaultMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have more than one default button of a given type..
        /// </summary>
        internal static string TaskDialogOnlyOneDefaultControl {
            get {
                return ResourceManager.GetString("TaskDialogOnlyOneDefaultControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value provided must be greater than the minimum value..
        /// </summary>
        internal static string TaskDialogProgressBarMaxValueGreaterThanMin {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarMaxValueGreaterThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value provided must be a positive number..
        /// </summary>
        internal static string TaskDialogProgressBarMinValueGreaterThanZero {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarMinValueGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value provided must less than the maximum value..
        /// </summary>
        internal static string TaskDialogProgressBarMinValueLessThanMax {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarMinValueLessThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value provided must be greater than equal to the minimum value and less than the maximum value..
        /// </summary>
        internal static string TaskDialogProgressBarValueInRange {
            get {
                return ResourceManager.GetString("TaskDialogProgressBarValueInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog cannot display both non-standard buttons and standard buttons..
        /// </summary>
        internal static string TaskDialogSupportedButtonsAndButtons {
            get {
                return ResourceManager.GetString("TaskDialogSupportedButtonsAndButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog cannot display both non-standard buttons and command links..
        /// </summary>
        internal static string TaskDialogSupportedButtonsAndLinks {
            get {
                return ResourceManager.GetString("TaskDialogSupportedButtonsAndLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown dialog control type..
        /// </summary>
        internal static string TaskDialogUnkownControl {
            get {
                return ResourceManager.GetString("TaskDialogUnkownControl", resourceCulture);
            }
        }
    }
}
