//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Error.Reporting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krypton.Toolkit.Suite.Extended.Error.Reporting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        internal static string Copied_to_clipboard {
            get {
                return ResourceManager.GetString("Copied to clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        internal static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this problem persists, please contact {0} support..
        /// </summary>
        internal static string ExceptionReportView_PopulateReportInfo_If_this_problem_persists__please_contact__0__support_ {
            get {
                return ResourceManager.GetString("ExceptionReportView_PopulateReportInfo_If_this_problem_persists__please_contact__" +
                        "0__support_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending report.
        /// </summary>
        internal static string ExceptionReportView_ShowError_Error_sending_report {
            get {
                return ResourceManager.GetString("ExceptionReportView_ShowError_Error_sending_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Detail.
        /// </summary>
        internal static string ExceptionReportView_ToggleShowFullDetail_Less_Detail {
            get {
                return ResourceManager.GetString("ExceptionReportView_ToggleShowFullDetail_Less_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Detail.
        /// </summary>
        internal static string ExceptionReportView_ToggleShowFullDetail_More_Detail {
            get {
                return ResourceManager.GetString("ExceptionReportView_ToggleShowFullDetail_More_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard copy failed.
        /// </summary>
        internal static string Failed_to_copy_to_clipboard {
            get {
                return ResourceManager.GetString("Failed to copy to clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send report.
        /// </summary>
        internal static string Failed_to_send_report {
            get {
                return ResourceManager.GetString("Failed to send report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed trying to report an Error.
        /// </summary>
        internal static string Failed_trying_to_report_an_Error {
            get {
                return ResourceManager.GetString("Failed trying to report an Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Forward {
            get {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hard_Disk {
            get {
                object obj = ResourceManager.GetObject("Hard_Disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a brief explanation of events leading up to this exception.
        /// </summary>
        internal static string Please_enter_a_brief_explanation_of_events_leading_up_to_this_exception {
            get {
                return ResourceManager.GetString("Please enter a brief explanation of events leading up to this exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report sent.
        /// </summary>
        internal static string Report_sent {
            get {
                return ResourceManager.GetString("Report sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Loc.
        /// </summary>
        internal static string TestLoc {
            get {
                return ResourceManager.GetString("TestLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following details can be used to obtain support for this application.
        /// </summary>
        internal static string The_following_details_can_be_used_to_obtain_support_for_this_application {
            get {
                return ResourceManager.GetString("The following details can be used to obtain support for this application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to {0}.
        /// </summary>
        internal static string to__0_ {
            get {
                return ResourceManager.GetString("to {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file.
        /// </summary>
        internal static string Unable_to_save_file {
            get {
                return ResourceManager.GetString("Unable to save file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to setup.
        /// </summary>
        internal static string Unable_to_setup {
            get {
                return ResourceManager.GetString("Unable to setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
