//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Software.Updater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krypton.Toolkit.Suite.Extended.Software.Updater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Details.
        /// </summary>
        internal static string SharpUpdateAcceptForm_btnDetails {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_btnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&amp;o.
        /// </summary>
        internal static string SharpUpdateAcceptForm_btnNo {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string SharpUpdateAcceptForm_btnYes {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version: {0}.
        /// </summary>
        internal static string SharpUpdateAcceptForm_lblNewVersion {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_lblNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available!
        ///Would you like to update?.
        /// </summary>
        internal static string SharpUpdateAcceptForm_lblUpdateAvail {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_lblUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Update Available.
        /// </summary>
        internal static string SharpUpdateAcceptForm_Title {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} of {1}.
        /// </summary>
        internal static string SharpUpdateDownloadForm_DownloadProgress {
            get {
                return ResourceManager.GetString("SharpUpdateDownloadForm_DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying Download....
        /// </summary>
        internal static string SharpUpdateDownloadForm_DownloadsFinished {
            get {
                return ResourceManager.GetString("SharpUpdateDownloadForm_DownloadsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        internal static string SharpUpdateDownloadForm_lblDownloading {
            get {
                return ResourceManager.GetString("SharpUpdateDownloadForm_lblDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Update.
        /// </summary>
        internal static string SharpUpdateDownloadForm_Title {
            get {
                return ResourceManager.GetString("SharpUpdateDownloadForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Back.
        /// </summary>
        internal static string SharpUpdateInfoForm_btnBack {
            get {
                return ResourceManager.GetString("SharpUpdateInfoForm_btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string SharpUpdateInfoForm_lblDescription {
            get {
                return ResourceManager.GetString("SharpUpdateInfoForm_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Update Info.
        /// </summary>
        internal static string SharpUpdateInfoForm_Title {
            get {
                return ResourceManager.GetString("SharpUpdateInfoForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version: {0}\nUpdate version: {1}.
        /// </summary>
        internal static string SharpUpdateInfoForm_Version {
            get {
                return ResourceManager.GetString("SharpUpdateInfoForm_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update cannot start.
        ///Please close all instances of this application to continue!.
        /// </summary>
        internal static string SharpUpdater_DoubleInstanceWarning {
            get {
                return ResourceManager.GetString("SharpUpdater_DoubleInstanceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Warning.
        /// </summary>
        internal static string SharpUpdater_DoubleInstanceWarningTitle {
            get {
                return ResourceManager.GetString("SharpUpdater_DoubleInstanceWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update download was cancelled.\nThis program has not been modified..
        /// </summary>
        internal static string SharpUpdater_DownloadCancelled {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Download Cancelled.
        /// </summary>
        internal static string SharpUpdater_DownloadCancelledTitle {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem downloading the update.\nPlease try again later..
        /// </summary>
        internal static string SharpUpdater_DownloadProblem {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Download Error.
        /// </summary>
        internal static string SharpUpdater_DownloadProblemTitle {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadProblemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap throbber_80 {
            get {
                object obj = ResourceManager.GetObject("throbber_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
