namespace Krypton.Toolkit.Suite.Extended.AdvancedDataGridView;

public delegate void AdvancedDataGridViewSearchToolBarSearchEventHandler(object sender, AdvancedDataGridViewSearchToolBarSearchEventArgs e);