#region BSD License
/*
 * Use of this source code is governed by a BSD-style
 * license or other governing licenses that can be found in the LICENSE.md file or at
 * https://raw.githubusercontent.com/Krypton-Suite/Extended-Toolkit/master/LICENSE
 */
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Settings.Run {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class RunDialogSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RunDialogSettings defaultInstance = ((RunDialogSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RunDialogSettings())));
        
        public static RunDialogSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysElevateNewTasks {
            get {
                return ((bool)(this["AlwaysElevateNewTasks"]));
            }
            set {
                this["AlwaysElevateNewTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlwaysShowSettingsButton {
            get {
                return ((bool)(this["AlwaysShowSettingsButton"]));
            }
            set {
                this["AlwaysShowSettingsButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlwaysShowProcessIcon {
            get {
                return ((bool)(this["AlwaysShowProcessIcon"]));
            }
            set {
                this["AlwaysShowProcessIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseLaunchProcessArguements {
            get {
                return ((bool)(this["UseLaunchProcessArguements"]));
            }
            set {
                this["UseLaunchProcessArguements"] = value;
            }
        }
    }
}
