#region BSD License
/*
 * Use of this source code is governed by a BSD-style
 * license or other governing licenses that can be found in the LICENSE.md file or at
 * https://raw.githubusercontent.com/Krypton-Suite/Extended-Toolkit/master/LICENSE
 */
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class CustomColourSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CustomColourSettings defaultInstance = ((CustomColourSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CustomColourSettings())));
        
        public static CustomColourSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourOne {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourOne"]));
            }
            set {
                this["CustomColourOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourTwo {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourTwo"]));
            }
            set {
                this["CustomColourTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourThree {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourThree"]));
            }
            set {
                this["CustomColourThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourFour {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourFour"]));
            }
            set {
                this["CustomColourFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourFive {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourFive"]));
            }
            set {
                this["CustomColourFive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourSix {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourSix"]));
            }
            set {
                this["CustomColourSix"] = value;
            }
        }
    }
}
