#region BSD License
/*
 * Use of this source code is governed by a BSD-style
 * license or other governing licenses that can be found in the LICENSE.md file or at
 * https://raw.githubusercontent.com/Krypton-Suite/Extended-Toolkit/master/LICENSE
 */
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class TextColourSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TextColourSettings defaultInstance = ((TextColourSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TextColourSettings())));
        
        public static TextColourSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color AlternativeNormalTextColour {
            get {
                return ((global::System.Drawing.Color)(this["AlternativeNormalTextColour"]));
            }
            set {
                this["AlternativeNormalTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DisabledTextColour {
            get {
                return ((global::System.Drawing.Color)(this["DisabledTextColour"]));
            }
            set {
                this["DisabledTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color FocusedTextColour {
            get {
                return ((global::System.Drawing.Color)(this["FocusedTextColour"]));
            }
            set {
                this["FocusedTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color NormalTextColour {
            get {
                return ((global::System.Drawing.Color)(this["NormalTextColour"]));
            }
            set {
                this["NormalTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PressedTextColour {
            get {
                return ((global::System.Drawing.Color)(this["PressedTextColour"]));
            }
            set {
                this["PressedTextColour"] = value;
            }
        }
    }
}
