//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Suite.Extended.Settings.Settings.Specialised_Dialogs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class SpecialisedDialogBooleanSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SpecialisedDialogBooleanSettings defaultInstance = ((SpecialisedDialogBooleanSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SpecialisedDialogBooleanSettings())));
        
        public static SpecialisedDialogBooleanSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRunDialogUACShieldShown {
            get {
                return ((bool)(this["IsRunDialogUACShieldShown"]));
            }
            set {
                this["IsRunDialogUACShieldShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLocateButton {
            get {
                return ((bool)(this["ShowLocateButton"]));
            }
            set {
                this["ShowLocateButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRunButtonDropDown {
            get {
                return ((bool)(this["EnableRunButtonDropDown"]));
            }
            set {
                this["EnableRunButtonDropDown"] = value;
            }
        }
    }
}
