namespace Krypton.Toolkit.Suite.Extended.Core;

public enum AllAvailableColourTypes
{
    AlternativeNormalTextColour = 0,
    BaseColour = 1,
    BorderColour = 2,
    CustomColourOne = 3,
    CustomColourTwo = 4,
    CustomColourThree = 5,
    CustomColourFour = 6,
    CustomColourFive = 7,
    CustomColourSix = 8,
    CustomTextColourOne = 9,
    CustomTextColourTwo = 10,
    CustomTextColourThree = 11,
    CustomTextColourFour = 12,
    CustomTextColourFive = 13,
    CustomTextColourSix = 14,
    DarkestColour = 15,
    DisabledControlColour = 16,
    DisabledTextColour = 17,
    FocusedTextColour = 18,
    LightColour = 19,
    LightestColour = 20,
    LinkDisabledColour = 21,
    LinkHoverColour = 22,
    LinkNormalColour = 23,
    LinkVisitedColour = 24,
    MediumColour = 25,
    MenuTextColour = 26,
    NormalTextColour = 27,
    PressedTextColour = 28,
    StatusTextColour = 29,
}